/**
 * Envelope patterns: a text syntax parsed into a `Pattern`, run against an
 * `Envelope` to yield the paths it matches and the captures it names. dCBOR
 * patterns embed at the leaves (`cbor(/…/)`). Formatting the paths lives on
 * `/format`.
 *
 * @packageDocumentation
 */
export { Interval, Quantifier, Reluctance } from "@blockchaincommons/dcbor-pattern";
export type { PatternRegex, RegexInput } from "@blockchaincommons/dcbor-pattern";
export {
  EnvelopePatternError,
  EnvelopePatternErrorCode,
  type EnvelopePatternErrorDetails,
  type EnvelopePatternErrorDetailsByCode,
  type EnvelopePatternErrorTyped,
  type DcborResult,
  type Span,
  type TokenKind,
  span,
} from "./error";
export {
  type Pattern,
  type LeafPattern,
  type StructurePattern,
  type MetaPattern,
  type CborPattern,
  type AssertionsPattern,
  type DigestPattern,
  type NodePattern,
  type ObjectPattern,
  type ObscuredPattern,
  type PredicatePattern,
  type SubjectPattern,
  type WrappedPattern,
  type Path,
  type MatchResult,
  paths,
  matches,
  display,
  pathsWithCaptures,
  patternEquals,
} from "./pattern";
export {
  // leaf patterns
  anyCbor,
  cbor,
  anyBool,
  boolean,
  anyText,
  text,
  textRegex,
  anyDate,
  date,
  dateRange,
  dateEarliest,
  dateLatest,
  dateIso8601,
  dateRegex,
  anyNumber,
  number,
  numberRange,
  numberGreaterThan,
  numberGreaterThanOrEqual,
  numberLessThan,
  numberLessThanOrEqual,
  numberNaN,
  anyByteString,
  byteString,
  byteStringRegex,
  anyKnownValue,
  knownValue,
  knownValueNamed,
  knownValueRegex,
  unit,
  anyArray,
  arrayWithRange,
  arrayWithCount,
  anyMap,
  mapWithRange,
  mapWithCount,
  nullValue,
  anyTagged,
  tagged,
  taggedName,
  taggedRegex,
  // structure patterns
  leaf,
  anyAssertion,
  assertionWithPredicate,
  assertionWithObject,
  anySubject,
  subject,
  anyPredicate,
  predicate,
  anyObject,
  object,
  digest,
  digestPrefix,
  digestBinaryRegex,
  anyNode,
  nodeWithAssertionsRange,
  nodeWithAssertionsCount,
  obscured,
  elided,
  encrypted,
  compressed,
  wrapped,
  unwrap,
  // meta patterns
  any,
  and,
  or,
  not,
  traverse,
  search,
  repeat,
  group,
  capture,
} from "./pattern/constructors";
export { parseEnvelopePattern, tryParseEnvelopePattern, type ParseOptions } from "./parse";
